pipeline{
    agent any
    stages{
        stage('version-ctrl'){
            steps{
                 git branch: 'webapp', url: 'https://github.com/devsecopsmurali/Java_Web_App.git'
            }
        }
         stage('Build-clean') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
       
    }
}

