pipeline{
    agent any
    environment{
        NEXUS_RELEASE_REPO ="mylibs-Release"
        NEXUS_SNAP_REPO="mylibs-Snapshot"
        NEXUS_CENTRAL_REPO ="mylibs-maven-central"
        NEXUS_GRP_REPO="mylibs-Group"
        NEXUS_USER="admin"
        NEXUS_PASS="admin"
        NEXUS_VERSION = "nexus3"
        NEXUS_PROTOCOL = "http"
        NEXUSPORT="8081"
        NEXUSIP = "18.234.106.112"
       //NEXUS_CREDENTIAL_ID = "nexuslogin"
        ARTVERSION = "${env.BUILD_ID}"
    }

    stages{
         stage('version-ctrl'){
            steps{
                 git branch: 'nexus_jenkins', url: 'https://github.com/devsecopsmurali/Java_Web_App.git'
            }
        }
        
        stage('BUILD'){
            steps {
                sh 'mvn -s settings.xml -DskipTests  clean install '
            }
        }

    }
}